### ISSUE TITLE
Ajax error + DB permission issue?

### ISSUE THREAD

**Issue by eltiel** [jokob-sk/Docker-Image-for-Pi.Alert#10]
Getting this weird error whenever I click on most of the UI:

![image](https://user-images.githubusercontent.com/11868456/171798314-8941eb75-3687-49a7-b2f9-f788ba7668d2.png)

Also, it seems nothing is being written onto the pialert.db as I get this error when trying to delete events:

![image](https://user-images.githubusercontent.com/11868456/171798891-a84bd955-54ff-4906-ae9f-9a3df81bcad9.png)

It's not a permission issue as the Docker successfully created the db file, but it remains as 0KB throughout.

**Comment by jokob-sk** [comment]
hey there! regrettably I can't seem to be able to reproduce the issue. You can try to `ssh` into the container and check the log files under `/home/pi/log` to see if there are any obvious error messages.

**Comment by jokob-sk** [comment]
FYI Moved the dockerfile into this repo https://github.com/jokob-sk/Pi.Alert/

**Comment by eltiel** [comment]
I gave up on the dockerfile and installed Pi Alert using the manual method and it worked. I'll try checking the logs when I can
