### ISSUE TITLE
GMT displayed instead of TZ

### ISSUE THREAD

**Issue by adammckay** [jokob-sk/Docker-Image-for-Pi.Alert#11]
This is a great effort!  Thank you for your dedication to getting PiAlert in a good container.

When I set my environment TZ=America/New_York, it works fine.  I can bash in and see that the date command yields:
Fri Jun 10 06:39:10 EDT 2022

So it seems all is working correctly there.  But PiAlert itself still displays everything in GMT.  All date/time columns are GMT.  Forgive me if this is more of a PiAlert issue.  I'm not sure but it would be nice to fix or know how to fix that.

**Comment by jokob-sk** [comment]
Hey, moved the Dockerfile into this fork and copied over the issue: https://github.com/jokob-sk/Pi.Alert/issues/7
