### ISSUE TITLE
How to backup the data?

### ISSUE THREAD

**Issue by rogierlommers** [jokob-sk/Docker-Image-for-Pi.Alert#2]
I tried to mount the `/home/pi/pialert/db` directory to the host, but then it does not work. It looks like the initial migrations do not run then.

Therefore my question: how do you backup your pi-alert instance?

**Comment by jokob-sk** [comment]
Hi mate! It's clunky, but I ssh into the instance and run:

`cp /home/pi/pialert/db/pialert.db /home/pi/pialert/config/pialert_2022_01_13.db_bak`

I've mounted /home/pi/pialert/config to persistent storage
I should probably add a cron job or something for this to happen automatically, but I don't need to back up the db that often - maybe I'll automate it later. Does this help?

**Comment by jokob-sk** [comment]
I've added a cron job to backup the DB every 30 min into the /config folder - check the README for details and let me know any feedback

**Comment by rogierlommers** [comment]
> I've added a cron job to backup the DB every 30 min into the /config folder - check the README for details and let me know any feedback

Thanks! I tried to check-out the commit where you add the cronab entry. But I cannot find it, where is it? When I pull the latest version, I indeed see the new entry in the output of `crontab -l`. But I cannot see how you added that into the docker image.

**Comment by rogierlommers** [comment]
Never mind, [found it](https://github.com/jokob-sk/Pi.Alert/blob/main/install/pialert.cron). I didn't notice that you were also the creator of the app itself 😀.

**Comment by jokob-sk** [comment]
Hey, I'm just building on top of the existing application built by https://github.com/pucherot/Pi.Alert. Full credit to the author. It looks like the project was abandoned so I added a few minor features and created a docker image so it's more accessible than a stand-alone install.

**Comment by rogierlommers** [comment]
Hey @jokob-sk , I just checked out the cron'tabbed backup feature. This works: I indeed see backup files in the `config` directory, which is mounted to the host.

The problem is that I need to restore the database every time the container goes down. Can we also think of a solution where the actual database (which is used inside the container) can be mounted to the host? This would be way better and more resilient.

**Comment by jokob-sk** [comment]
Hey,

Good to hear the backup works! What I can do is copy the _bak file on
system reboot with a cron job to the DB folder and rename it so it
overwrites the default DB. Yes, there will be some data loss, but restoring
will be automatic and those are only a few data points. Let me know if you
have a better idea - I also tried mounting the /db folder with no luck.
Cheers!

**Comment by rogierlommers** [comment]
> Hey, Good to hear the backup works! What I can do is copy the _bak file on system reboot with a cron job to the DB folder and rename it so it overwrites the default DB. Yes, there will be some data loss, but restoring will be automatic and those are only a few data points. Let me know if you have a better idea - I also tried mounting the /db folder with no luck. Cheers!

Your suggestion would indeed work. However, we can also figure out why we can't mount the db file to the host :). I think it has something to do with permissions of the docker deamon. Did you try to mount the database FILE or the directory of the database to the host? (see this: https://stackoverflow.com/a/67874709)

**Comment by jokob-sk** [comment]
Yep, probably something permissions related. Couldn't figure it out though.
Let me know if you have better luck! I'm a bit busy these days, but I'll
try to have a look at a later date.

**Comment by rogierlommers** [comment]
I'm trying to figure it out.... also created this post here: https://discourse.linuxserver.io/t/pgid-and-puid-for-other-containers/3869

I'll keep you posted here!

**Comment by pbek** [comment]
This is what I do:

```yaml
...
    volumes:
      - pialert_db:/home/pi/pialert/db
      - ./pialert/pialert.conf:/home/pi/pialert/config/pialert.conf
      - ./pialert/version.conf:/home/pi/pialert/config/version.conf
...
```

I use a named volume `pialert_db` as my db directory and I mount the two config files from a local folder to their places in the config folder. On my server I backup the `docker-compose.yaml` folder and the docker volumes folder.

**Comment by pbek** [comment]
My whole config looks something like this:

```yaml
  pialert:
    image: jokobsk/pi.alert
    ports:
      - "80:20211/tcp"
    environment:
      - TZ=Europe/Vienna
    networks:
      local:
        ipv4_address: 192.168.1.2
    restart: unless-stopped
    volumes:
      - pialert_db:/home/pi/pialert/db
      - ./pialert/pialert.conf:/home/pi/pialert/config/pialert.conf
      - ./pialert/version.conf:/home/pi/pialert/config/version.conf
```

I don't use the host network, I give the container it's own static ip (`192.168.1.2` in this example).
I mapped a port for this example. My real config uses traefik (with let's encrypt) as ingress router and authelia for authentication.

**Comment by jokob-sk** [comment]
FYI Moved the dockerfile into this repo https://github.com/jokob-sk/Pi.Alert/

**Comment by Macleykun** [comment]
This is also fixed see https://github.com/jokob-sk/Pi.Alert/issues/9

**Comment by Macleykun** [comment]
Also I would suggest that this fork isn’t needed anymore (archive or delete?)
