### ISSUE TITLE
Shoutrrr

### ISSUE THREAD

**Issue by hillaliy** [jokob-sk/Docker-Image-for-Pi.Alert#3]
Hi first thanks for your great work.
Can you combine https://github.com/containrrr/shoutrrr to this wonderful project?

**Comment by jokob-sk** [comment]
Hey, I guess this would have to be added to the application itself, not docker file. Try opening a feature request here: https://github.com/fosspill/Pi.Alert/issues

**Comment by jokob-sk** [comment]
FYI moved the docker file and your issue here: https://github.com/jokob-sk/Pi.Alert/issues/8
