### ISSUE TITLE
batabase reset everytime docker rebuilt

### ISSUE THREAD

**Issue by kjames2001** [jokob-sk/Docker-Image-for-Pi.Alert#5]
i loose my database everytime i rebuild the docker.

tried mount the dir to an external volume, then iptables wont load.

**Comment by rogierlommers** [comment]
Kind of related: https://github.com/jokob-sk/Docker-Image-for-Pi.Alert/issues/2

**Comment by kjames2001** [comment]
thanks for the tip, but he's using docker compose, anyway to convert it to docker run or unraid template?

**Comment by kwschnei** [comment]
Give this a try for your docker-compose.yml (sorry, the formatting isn't great, but the only addition is the very last line):

version: '3.4'
services:
  pialert:
    container_name: pialert
    image: jokobsk/pi.alert
    restart: always
    network_mode: host
    volumes:
      - ./config:/home/pi/pialert/config
      - ./db:/home/pi/pialert/db

**Comment by kjames2001** [comment]
what i did is run 'docker volume create pialert_db'

Then mount the volume using '-v pialert_db:/home/pi/pialert/db

basicly what [pbek](https://github.com/pbek) suggested!

That seems to work. 

however, i still cant have the db file where i want it to be, which is in '/mnt/user/appdata/pialert/db'. that just bothers me. lol

**Comment by jnaav** [comment]
> however, i still cant have the db file where i want it to be, which is in '/mnt/user/appdata/pialert/db'. that just bothers me. lol

Same here.

- Tried to map de config folder. Did not work.
- Tried to map de db file. Did not work
- Tried to generate de db inside the container, copy that file to my folder and the map the file to that file. Did not work.

Only create a volume worked, but I prefer to have direct access to that file. Why is that not possible?

**Comment by jokob-sk** [comment]
FYI Moved the dockerfile into this repo https://github.com/jokob-sk/Pi.Alert/ and opened a related issue there https://github.com/jokob-sk/Pi.Alert/issues/9

**Comment by Macleykun** [comment]
This is also fixed see https://github.com/jokob-sk/Pi.Alert/issues/9
