### ISSUE TITLE
nmap support

### ISSUE THREAD

**Issue by kwschnei** [jokob-sk/Docker-Image-for-Pi.Alert#6]
This is something I'd normally request in the base GitHub, however, it really looks like the project owner has stopped maintaining it.

[cjd/Pi.Alert](https://github.com/cjd/Pi.Alert) has added nmap support to Pi.Alert. Is this something you would consider adding to your image?

**Comment by jokob-sk** [comment]
Hi there, yes, hopefully in the near future I'll merge it once it's ready

**Comment by jokob-sk** [comment]
FYI Moved the dockerfile into this repo https://github.com/jokob-sk/Pi.Alert/
