### ISSUE TITLE
Improve dockerfile

### ISSUE THREAD

**Issue by Macleykun** [jokob-sk/Docker-Image-for-Pi.Alert#7]
Heya, i saw ya dockerfile and i'm curious to use pi.alert myself.

I do want to ask before i use it myself, can you use this project withoud using the host interface and just use the bridge one?

Aside of the above, i'm more familiar with Docker and would love to submit a PR to improve the Dockerfile :-)

I think the first thing is to just fork the pi.alert project of your choosing (one that's maintained/has the most features).

The reason is that i saw this: https://github.com/jokob-sk/Docker-Image-for-Pi.Alert/blob/main/Dockerfile#L32

---

When making a Docker image, you want to have the most control and limit differences as much as possible. So if i would rebuild the image from your Dockerfile with the project files from the same time, it should be same interms of dependency versions.

Don't focus to much on this in the beginning, most people ignore specyfing the exact depedency versions :-) even the image in most cases.

---

If you have pi.alert project of your choosing in github, instead of installing git, cloning the repo and then doing some clever editting. You can make the needed changes in the configs on the project. And we just copy those changes.

You might have seen: `COPY . .` (which copies the entire project the Dockerfile is in, into the container workdir).

---

I think only doing this will greatly reduce the amount of steps. Next i would condence every apt step into just a single apt install.

So instead of doing:

```
RUN apt update \
    && apt $myinstall -y \
    && apt $myinstall apt-utils -y \
    && apt $myinstall cron -y \
    && apt install git -y \
    && apt $myinstall sudo -y

#add the pi user
RUN useradd -ms /bin/bash pi 
WORKDIR /home/pi
# Lighttpd & PHP
RUN apt $myinstall lighttpd -y \
    && mv /var/www/html/index.lighttpd.html /var/www/html/index.lighttpd.html.old \
    && ln -s ~/pialert/install/index.html /var/www/html/index.html \
    && apt $myinstall php php-cgi php-fpm php-sqlite3 -y \
    && lighttpd-enable-mod fastcgi-php \
    && apt $myinstall sqlite3 -y
```

It's better to do this: (includ -y also in your ARG :))

```
RUN apt-get update && \
        apt-get install $myinstall apt-utils cron sudo (etc)
```

---

also, you don't need to use sudo in a dockerfile ever :). You usually build everything as root, then create a none-root user, change perms and then switch over. But this is also something most people don't do, so i wouldn't focus on this either.

---

Another suggestion, tho this is more of a feature of git (and also tar). You can do chmod +x on your script, push these changes to your github repo. And you'll notice you will have an empty commit but the permissions are changed!

Doing the copy action then copies the permissions over (i would use copy, but add is technically better so i'll leave the one up to you :)) so that also saves a step.

---

I wouldn't create a script to then run the script which then starts lighttpd, cron and tail nothing.
While i assume lighthttpd normally is enabled (auto start at boot) with cron doing this also normally by default. You could also start with a more suitable docker image to save yourself some work like using the lighthttpd image: https://hub.docker.com/r/sebp/lighttpd (not official but seeing the amount of pulls, it's a good one imo).

I don't see why the person also uses a script to start the container (CMD). But i would say specifying:
lighttpd -D -f /etc/lighttpd/lighttpd.conf should be enough in CMD.

---

I know it's alot of info :) but i wouldn't mind to make your a PR. You do need to update your fork with a pi.alert so i can do it properly tho :)

**Comment by jokob-sk** [comment]
Oh man this is amazing info. I'm on vacation and will be back in June to
dive into this more. It will take some time to digest 😁 but I'm looking
forward to learning more.

**Comment by Macleykun** [comment]
Np enjoy ya vacation!
I won’t use the image myself, bc the network system I actually use have it buildin. So I’m actually better off using that and proxy to that page :p.

Just reopen this issue/ping me when you have the repo ready as asked (and have tried some optimization yourself/verified everything works and is written well for compose).

**Comment by jokob-sk** [comment]
Hi there! Had some time to look at your suggestions and I'm not sure if I follow some of them. With the `COPY . .` suggestion, you mean to create a temporary build image and to copy the relevant files after as described here? https://janakerman.co.uk/docker-git-clone/

I did implement the suggestion to install everything in one command which clean up the dockerfile quite a bit, thanks! :)  

The selected fork is one I manage as none of the others with additional features (e.g. NMAP support) seem to work so far on the targeted environments (linux/arm64, linux/arm/v7, linux/arm64).

I understand I can use a different base image, however I had quite a bit of troubles getting it working on the selected debian image. Most issues were probably caused by the original application being built for Raspberrian with the pi user home directory as target installation path (needs to be cleaned up in the application first probably). So I'm hesitant revamping the image with what I see are no big benefits? Feel free to prove me wrong :)  Maybe I'll feel like doing that in the future though, so definitely a good suggestion. 

Feel free to have a look at the updated Dockerfile and provide a PR or suggestions directly. Thanks!

**Comment by Macleykun** [comment]
> Hi there! Had some time to look at your suggestions and I'm not sure if I follow some of them. With the `COPY . .` suggestion, you mean to create a temporary build image and to copy the relevant files after as described here? https://janakerman.co.uk/docker-git-clone/
> 
> I did implement the suggestion to install everything in one command which clean up the dockerfile quite a bit, thanks! :)
> 
> The selected fork is one I manage as none of the others with additional features (e.g. NMAP support) seem to work so far on the targeted environments (linux/arm64, linux/arm/v7, linux/arm64).
> 
> I understand I can use a different base image, however I had quite a bit of troubles getting it working on the selected debian image. Most issues were probably caused by the original application being built for Raspberrian with the pi user home directory as target installation path (needs to be cleaned up in the application first probably). So I'm hesitant revamping the image with what I see are no big benefits? Feel free to prove me wrong :) Maybe I'll feel like doing that in the future though, so definitely a good suggestion.
> 
> Feel free to have a look at the updated Dockerfile and provide a PR or suggestions directly. Thanks!

correct, so as you do here: https://github.com/jokob-sk/Docker-Image-for-Pi.Alert/blob/main/Dockerfile#L22
You only really want to get the files from: https://github.com/jokob-sk/Pi.Alert
B/c you only add a dockerfile (And maybe some instructions). It's way easier and simpler to fork from the upstream as you done, and add the docker stuff from this repo in there, and then remove this repo we are currently discussing in.

Why? Let's say i fork your repo (with the dockerfile stuff) and want to make an edit, test it locally using docker. I then see i don't have my change in the container b/c instead of using the local files with a COPY .  ., it cloned it from your repo online instead. Not something you should do in a dockerfile.

I would definitly do the above first, before i'll make a PR with some improvements and such :)

i'm not sure about the part of the base image, i can't find that back in my wording but i wouldn't change the base either. It's a slim debian one and is gud in my eyes!

so just to be clear, you can copy the content of this repo to the new one you made (forked one) and append your docker readme to the current readme in that fork (or merge). Just don't overwrite the license (i don't think ya allowed to do that).

**Comment by jokob-sk** [comment]
Ah...maybe I'm slowly getting it, you mean I should add the `Dockerfile` to this fork I manage https://github.com/jokob-sk/Pi.Alert (or add the files from that fork to this repo). The idea is to have both, the code and dockerfile in one repo, correct?  Then work only with one repo which contains both, the application code and the docker file, instead using git clone in the container directly. Am I on the right path?

**Comment by Macleykun** [comment]
Yes the first ya mentioned is what I think is best, if for whatever reason the dude you forked makes an update, you can either push your changes easier back or keep ya fork easier up to date.

And correct, both docker file and code should be in the same repo!

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: jokob-sk ***@***.***>
Verzonden: Friday, June 10, 2022 10:18:46 AM
Aan: jokob-sk/Docker-Image-for-Pi.Alert ***@***.***>
CC: Macley ***@***.***>; State change ***@***.***>
Onderwerp: Re: [jokob-sk/Docker-Image-for-Pi.Alert] Improve dockerfile (Issue #7)


Ah...maybe I'm slowly getting it, you mean I should add the Dockerfile to this fork I manage https://github.com/jokob-sk/Pi.Alert (or add the files from that fork to this repo). The idea is to have both, the code and dockerfile in one repo, correct? Then work only with one repo which contains both, the application code and the docker file, instead using git clone in the container directly. Am I on the right path?

**Comment by jokob-sk** [comment]
Cool thanks for the detailed explanation, maybe I'll have a go at it over the next few days. This will also make the image a bit smaller not needing git installed in the first place. Cheers! 😉

**Comment by Macleykun** [comment]
True! You can also make a docker exception file (google about that) if you don’t need all the files. However if we’re talking about a small difference, It isn’t worth it imo

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: jokob-sk ***@***.***>
Verzonden: Friday, June 10, 2022 10:24:44 AM
Aan: jokob-sk/Docker-Image-for-Pi.Alert ***@***.***>
CC: Macley ***@***.***>; State change ***@***.***>
Onderwerp: Re: [jokob-sk/Docker-Image-for-Pi.Alert] Improve dockerfile (Issue #7)


Cool thanks for the detailed explanation, maybe I'll have a go at it over the next few days. This will also make the image a bit smaller not needing git installed in the first place. Cheers! 😉

**Comment by jokob-sk** [comment]
FYI Moved the dockerfile into this repo https://github.com/jokob-sk/Pi.Alert/
